### ISSUE TITLE
Install bug error

### ISSUE THREAD

**Issue by chrnogirl** [ScarletStudy/DGS1-Android-Release#23] opened 2019-04-03 04:43 UTC
Below is the bug error I recieved. I have never tried to download an android base emulator before so Im sure I have no idea what I am doing. Do I create a japanese account and purchase the game first before installing Iris? Please help.

####################
# Version Info     #
####################

Code:7
Name: 1.1

####################
# Device Info      #
####################

board:              sdm845
bootloader:         G965USQS3CSAG
cpuAbi:             armeabi-v7a
cpuAbi2:            armeabi
device:             star2qltesq
display:            PPR1.180610.011.G965USQS3CSAG
hardware:           qcom
id:                 PPR1.180610.011
manufacturer:       samsung
model:              SM-G965U
product:            star2qltesq
tags:               release-keys
types:              user
user:               dpi

codename:           REL
incremental:        G965USQS3CSAG
release:            9
sdkInt:             28
sdk:                28

####################
# App Info         #
####################

Data Folder Exists:       True

Files:
	/storage/emulated/0/ScarletStudy/IrisMobile/error.log

####################
# APK Info         #
####################

Is Installed:  False
Is Accessable: False
Apk Path:      NA

####################
# OBB Folder Info  #
####################

Android/obb Exists:       True
Game OBB Folder Exists:   False
Backup OBB Folder Exists: False

Folders in Android/obb:
	/storage/emulated/0/Android/obb/com.brainbow.peak.app,
	/storage/emulated/0/Android/obb/com.facebook.katana,
	/storage/emulated/0/Android/obb/com.facebook.orca

Files in Game OBB Folder:
	None

Files in Backup OBB Folder:
	None

####################
# Error Message    #
####################

"The Great Ace Attorney" has not been installed.

####################
# Exception String #
####################

None

**Comment by an-error42** [comment] 2019-04-03 04:54
Indeed, DGS should be installed first from the Japanese Play store before attempting to patch.
You can find more information here in the [IrisMobile page](https://scarletstudy.gq/irismobile/) (Specifically, **Applying our Translation Patch to DGS** section which also includes a link to the purchasing guide).

Since the cause of the issue is already known, I'll be also closing it as well.
Feel free to contact us if you need further help. Thank you!

**Closed as completed by an-error42** 2019-04-03 04:54 UTC
